# Generated by Django 3.0.3 on 2020-02-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='demo', max_length=30)),
                ('teachRatings', models.CharField(default=23, max_length=30)),
            ],
        ),
    ]
